version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_map_frontend
    ports:
      - "80:80"
    restart: always
    environment:
      - NODE_ENV=production
      - PORT=80
      - HOSTNAME=0.0.0.0
